version: "3.9"

services:
  grafana:
    image: grafana/grafana:8.2.0
    ports:
      - 5000:3000
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - tempo
  loki:
    image: grafana/loki:2.3.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
  tempo:
    image: grafana/tempo:1.2.0
    command: [ "-search.enabled=true", "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml    
    ports:
      # tempo.
      # http://localhost:3200
      - 3200:3200
      # otlp grpc
      # http://localhost:4317
      - 4317:4317
      # otlp http.
      # http://localhost:4318
      - 4318:4318
  tracing-demo:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OTEL_PYTHON_LOG_CORRELATION=true      
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push